rename zh_cn to zh_cn.json
AlexModGuy/AlexsCaves pull request #442
Opened 2023-10-29 18:13 UTC by DocOrlande

2023-10-30 05:30 UTC, Don-Trueno commented
To @DocOrlande
Maybe you should check #433 first and if you want to submit yours, it's a good manner to contact me first.

----
To Alex @AlexModGuy :
With other translators' help, we find out that this version of translation is not good enough, so merging this pr may not be a good idea.

2023-10-30 06:03 UTC, JerryHan3 commented
TLDR: Duplicate with #433 and not that good enough for Chinese localization.

2023-10-30 06:33 UTC, JerryHan3 requested changes
These are only some of the translation issues, and many more are not mentioned yet. Besides, it's not that polite to replace all existing translations by one's perspective. In conclusion, I oppose applying the translation by DocOrlande, and we should keep the current edition of `zh_cn.json`.

2023-10-30 06:33 UTC, JerryHan3 commented on src/main/resources/assets/alexscaves/lang/zh_cn.json
> +  "item.alexscaves.gossamer_worm_bucket": "薄纱海蠕虫",
**Inappropriate translation.** This text means "Sea worm with thin silks", which doesn't match with the original text. 
```suggestion
  "item.alexscaves.gossamer_worm_bucket": "浮蚕桶",
```

2023-10-30 06:33 UTC, JerryHan3 commented on src/main/resources/assets/alexscaves/lang/zh_cn.json
> +  "alexscaves.sound.subtitle.darkness_incarnate_idle": "黑暗化身:颤抖",
All subtitle translations from line 831 to line 1152 don't match the existing format "<Sound source>：<Sound type>". They all need to be changed.

2023-10-30 06:33 UTC, JerryHan3 commented on src/main/resources/assets/alexscaves/lang/zh_cn.json
> +  "item.alexscaves.cave_book.utilities": "实用知识",
**Inappropriate translation**. New text means "Useful knowledges", which doesn't match the meaning of "**_utility_**".

2023-10-30 06:33 UTC, JerryHan3 commented on src/main/resources/assets/alexscaves/lang/zh_cn.json
> +  "item.alexscaves.game_controller": "Logitech F710游戏手柄",
**Inappropriate translation**. No need to specify which game controller it is.

2023-10-30 06:33 UTC, JerryHan3 commented on src/main/resources/assets/alexscaves/lang/zh_cn.json
> +  "block.alexscaves.cave_painting_mystery_9.desc": "\"神秘图案 IX\"",
**Improper quote marks.** These quote marks should use Chinese marks `“”` instead of English marks `""`.

2023-10-30 06:39 UTC, DocOrlande commented
To @Don-Trueno
I should apologize to you for my misoperation，I submit a file named wrongly without .json，I want to rename it but actually don't know how because it's my first time to submit files in github.

2023-10-30 07:03 UTC, DocOrlande commented
To @JerryHan3
Thank you for pointing out the issues of my translation,
However, there are more serious and obviously issues in the current zh_cn.json
For example:
Line130 "block.alexscaves.tree_star": "星树果",
Inappropriate translation. This text means "Star shaped tree furit", which doesn't match with the design.

Line331  "item.alexscaves.spelunkie": "硫心糖果",
Inappropriate translation. This text means "Sulfer candy", which doesn't match with the original text and the design.
Item spelunkie is based on a food "twinkies", which is apparently a layer cake.

Line332  "item.alexscaves.slam": "猛汉猪排",
Inappropriate translation. This text means "Strong Man Pork Chops", which doesn't match with the original text and the design.
Item slam is based on lunch meat,to be precise, it should be the CRAM steak lunch meat from the Fallout 4 game.

Line468  "entity.alexscaves.brainiac": "噬脑魔",
Inappropriate translation. This text of "噬脑魔" means "Demon of brain eat",which dosen't matchs the text and design.
This entity braniac may based on the same name character Brainiac（DC）

I don't think this version is good enough.

2023-10-30 08:40 UTC, Don-Trueno commented
> However, there are more serious and obviously issues in the current zh_cn.json
> I don't think this version is good enough.

I really hope you wouldn't nickel and dime with me and my translating, because it is offensive and unpleasing.

The four _issues_ listed above happened to previously discussed, which means they were chosen only because more translators preferred or all opinions not convincing enough. The exception is spelunkie, not to use 蛋糕 because 蛋糕 may refer to round glazed cake which already appers in vanilla game and most of other mods, this would be changed into 硫心蛋糕卷(roll cake with sulfur inside) later

Besides, what makes me think your translation not good enough could never be those nickels and dimes. I like new ideas, but you just made too many mistakes like wrong punctuations and inconsistent contexts.

Maybe you should read [Translation Standardization](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:ST) first, then I wish you could contribute more other mods and stop bothering me here.

2023-10-30 11:10 UTC, DocOrlande commented
To @Don-Trueno
Sure，I respect your thoughts, and I apologize for any confusion and discomfort it may have caused you.
I will be happy to enjoy the game with your translation.

2023-10-30 15:28 UTC, merged

2023-10-31 05:59 UTC, JerryHan3 commented
Sorry Alex, you might have misunderstood our opinion. We want to abandon the new version of translation, and close this pr, instead of merging it.